services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE test_pg;' -U postgres
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests/test_dbhandler.py
